// RULE: All prompts are built here. Never inline prompt strings in components or stores.

import type { StackConfig, ProjectPlan, Task } from "@/types";
import { stackOptions } from "@/components/stack/stackRegistry";
import { LATEST_VERSIONS } from "@/lib/versioning";

export function buildPlanAgentSystemPrompt(stack: StackConfig): string {
  const selectedItems = stackOptions.filter((o) =>
    stack.selected.includes(o.id),
  );
  const stackList = selectedItems
    .map((o) => `- ${o.label} (${o.packageName})`)
    .join("\n");

  return `You are an expert web application planning assistant for a local-first AI scaffolding studio called Jugaad.

Your role is to help the user plan their Next.js web application through a conversational flow.

Selected tech stack:
${stackList}

Guidelines:
- Ask clarifying questions to understand the app's purpose, features, pages, and data models.
- Keep questions focused and conversational — one topic at a time.
- When you have enough information to produce a complete plan, output it wrapped in <plan> tags as valid JSON matching this TypeScript type:

type ProjectPlan = {
  id: string;           // generate a UUID v4
  name: string;
  description: string;
  stack: { selected: string[] };
  features: { id: string; title: string; description: string }[];
  pages: { id: string; name: string; route: string; description: string }[];
  dataModels: { id: string; name: string; fields: { name: string; type: string; required: boolean }[] }[];
  authStrategy: "none" | "nextauth" | "clerk" | "firebase" | "custom";
  createdAt: number;    // Date.now()
  updatedAt: number;    // Date.now()
};

Example output when ready:
<plan>
{ "id": "...", "name": "...", ... }
</plan>

Do not produce the plan until you have gathered sufficient detail about features, pages, and data models.`;
}

export function buildTaskGeneratorPrompt(
  plan: ProjectPlan,
  docsContext: string,
): string {
  return `You are a principal-level Next.js architect and senior TypeScript engineer. Decompose the following project plan into a perfectly ordered list of file generation tasks. Each file will be generated by an LLM so every instruction must be precise, complete, and unambiguous.

Project Plan:
${JSON.stringify(plan, null, 2)}

Relevant Documentation:
${docsContext}

Rules:
1. Each task maps to exactly ONE file.
2. Output tasks in dependency order. A task may only import from files in EARLIER tasks. Declare deps in "dependsOn".
3. File paths use Next.js App Router convention (e.g. "app/dashboard/page.tsx"). No src/ prefix.
4. Every page.tsx and layout.tsx must have a default export.
5. Every route.ts must export at least one of GET/POST/PUT/DELETE.
6. First tasks must always be: package.json → tsconfig.json → postcss.config.mjs → next.config.ts → app/globals.css → types → utils → components → pages.
7. Include ALL necessary files: config, types, utils, stores, components, and pages. Do not omit any file the app needs to run.
8. PACKAGE VERSIONS: Use exact versions below. Never guess or use older versions.
   Core: next@${LATEST_VERSIONS["next"]}, react@${LATEST_VERSIONS["react"]}, react-dom@${LATEST_VERSIONS["react-dom"]}, typescript@${LATEST_VERSIONS["typescript"]}
   Tailwind v4: tailwindcss@${LATEST_VERSIONS["tailwindcss"]} (devDep), @tailwindcss/postcss@${LATEST_VERSIONS["@tailwindcss/postcss"]} (devDep). No autoprefixer. No old tailwindcss PostCSS plugin.
   State: zustand@${LATEST_VERSIONS["zustand"]}, zod@${LATEST_VERSIONS["zod"]}, react-hook-form@${LATEST_VERSIONS["react-hook-form"]}
9. TAILWIND v4: Do NOT generate tailwind.config.ts / tailwind.config.js. Tailwind v4 is CSS-first. postcss.config must use "@tailwindcss/postcss" only. globals.css must start with '@import "tailwindcss";' — no @tailwind directives.
10. "use client": Any file using React hooks, event handlers, or browser APIs must have "use client" as its absolute first line (before all imports). Server Components (data fetching, static) must NOT have it. Route handlers (route.ts) must NOT have it.
11. next.config.ts: Keep MINIMAL. Do NOT set typescript.ignoreBuildErrors or eslint.ignoreDuringBuilds — the app must produce zero errors and zero warnings. Only add config the app specifically needs.
12. tsconfig.json: Must use "strict": true, "noUnusedLocals": true, "noUnusedParameters": true, "noImplicitReturns": true, "noFallthroughCasesInSwitch": true. Must include paths: { "@/*": ["./*"] }, "jsx": "preserve", "moduleResolution": "bundler".
13. IMPORT ALIAS: All generated files use "@/" for local imports. Never relative paths ("../X", "./X").
14. NEVER import from "next/router" — use "next/navigation" (useRouter, usePathname, redirect, useParams, useSearchParams).
15. Every component or page doing async work must handle loading AND error states. No indeterminate UI states.
16. Design quality: Clean, minimal, polished UI. Real content — no lorem ipsum. Consistent Tailwind spacing (4-unit scale). Semantic HTML. Responsive 320px→1440px. Accessible: labels, aria attributes, keyboard navigation.
17. Prefer React Server Components for data fetching. Only use "use client" when genuine interactivity is required.
18. Task instructions must be specific: describe what the file exports, what props/types it uses, how it connects to other files, and any key implementation details.

Output the tasks as a JSON array wrapped in <tasks> tags. No other text outside the tags.

<tasks>
[
  {
    "id": "uuid-here",
    "title": "Short descriptive title",
    "filePath": "relative/path/to/file.tsx",
    "instruction": "Detailed instruction for generating this file",
    "dependsOn": [],
    "docsContext": "",
    "status": "pending",
    "retryCount": 0
  }
]
</tasks>`;
}

export function buildTaskExecutorPrompt(
  task: Task,
  dependencyFileContents: Record<string, string>,
): string {
  // RULE: The task executor system prompt must always say:
  // "Respond with only the raw file content. No explanations, no markdown fences, no commentary."
  const depsSection =
    Object.keys(dependencyFileContents).length > 0
      ? Object.entries(dependencyFileContents)
          .map(([path, content]) => `// FILE: ${path}\n${content}`)
          .join("\n\n---\n\n")
      : "None";

  // Per-file additional constraints injected based on path
  let fileSpecificRules = "";
  if (task.filePath === "package.json") {
    fileSpecificRules = `\nCRITICAL VERSION REQUIREMENTS (use exactly these — no older versions):
- next: "${LATEST_VERSIONS["next"]}", react: "${LATEST_VERSIONS["react"]}", react-dom: "${LATEST_VERSIONS["react-dom"]}"
- typescript: "${LATEST_VERSIONS["typescript"]}" (devDep)
- tailwindcss: "${LATEST_VERSIONS["tailwindcss"]}" (devDep), @tailwindcss/postcss: "${LATEST_VERSIONS["@tailwindcss/postcss"]}" (devDep)
- Do NOT include autoprefixer or the old tailwindcss PostCSS plugin — Tailwind v4 does not need them.
- zustand: "${LATEST_VERSIONS["zustand"]}" (if used), zod: "${LATEST_VERSIONS["zod"]}" (if used)\n`;
  } else if (task.filePath.match(/postcss\.config\.(js|mjs|ts)$/)) {
    fileSpecificRules = `\nCRITICAL: Use Tailwind v4 PostCSS config. The ONLY plugin must be "@tailwindcss/postcss". Do NOT use tailwindcss or autoprefixer as plugins.\n`;
  } else if (
    task.filePath.match(/globals\.css$/) ||
    task.filePath.match(/global\.css$/)
  ) {
    fileSpecificRules = `\nCRITICAL: Use Tailwind v4 CSS import. Start the file with '@import "tailwindcss";' — do NOT use @tailwind base/components/utilities directives.\n`;
  } else if (task.filePath.match(/tailwind\.config\.(ts|js|mjs)$/)) {
    fileSpecificRules = `\nCRITICAL: Tailwind v4 does not use a JavaScript config file. Instead, output a globals.css with '@import "tailwindcss";' and any theme customizations using @theme blocks. If you must output this file, make it minimal and note that v4 config is CSS-first.\n`;
  } else if (task.filePath.match(/next\.config\.(ts|js|mjs)$/)) {
    fileSpecificRules = `\nCRITICAL next.config.ts rules:
- Keep the config MINIMAL. The app must compile with zero TypeScript errors and zero ESLint errors — do NOT set typescript.ignoreBuildErrors or eslint.ignoreDuringBuilds.
- Do NOT add experimental flags unless the instruction explicitly requires them.
- If the app uses external images, add images.remotePatterns (NOT the deprecated images.domains).
- Correct minimal example:
    import type { NextConfig } from "next";
    const nextConfig: NextConfig = {};
    export default nextConfig;\n`;
  } else if (task.filePath === "tsconfig.json") {
    fileSpecificRules = `\nCRITICAL tsconfig.json rules — ALL of these are required, do not omit any:
- "strict": true — full strict mode. Your generated code must compile cleanly under it.
- "noUnusedLocals": true — every imported identifier must be used. Unused imports are TypeScript compile errors.
- "noUnusedParameters": true — every function parameter must be used (prefix unused-but-required params with _).
- "noImplicitReturns": true — every code path in a non-void function must return a value.
- "noFallthroughCasesInSwitch": true — switch cases must break or return.
- paths: { "@/*": ["./*"] } — required for the @/ import alias to resolve.
- "jsx": "preserve", "moduleResolution": "bundler" — required for Next.js App Router.\n`;
  }

  const qualityRules = `
You are a principal-level TypeScript/React engineer. Write production-grade, idiomatic code at the same quality bar as the Next.js core team. No shortcuts. No suppression comments. No placeholder code.

TYPESCRIPT STRICT COMPLIANCE (strict: true, noUnusedLocals: true, noUnusedParameters: true, noImplicitReturns: true are all enabled):
• Never use \`any\` — use \`unknown\` and narrow it, or use specific types. If a library forces \`any\`, cast through \`unknown\` with a comment.
• Explicitly type all function parameters. Declare non-obvious return types.
• Never use non-null assertion (!). Use optional chaining (?.) or explicit null checks.
• Never use type assertion (as T) unless you can prove it correct. Prefer type guards.
• Import ONLY identifiers you use in the file body. Unused imports are compile errors.
• Unused required parameters: prefix with _ (e.g. _event: React.MouseEvent).
• All code paths in non-void functions must return a value.
• Never add // @ts-ignore or // @ts-expect-error — fix the type error properly.
• Never add // eslint-disable comments — write code that passes ESLint without suppression.

"USE CLIENT" DIRECTIVE:
• REQUIRED on any file using: useState, useEffect, useRef, useCallback, useMemo, useContext, useReducer, useId, usePathname, useRouter, useSearchParams, useParams, or any browser API (window, document, localStorage, sessionStorage, navigator).
• Must be the ABSOLUTE FIRST LINE — before all import statements.
• Must NOT appear in route.ts/route.tsx files (always server-side).
• Must NOT appear in pure Server Components (no hooks, no browser APIs).

IMPORTS:
• "@/" alias for ALL local imports ("@/components/X", "@/lib/utils"). Never relative paths ("./X", "../X").
• Import from "next/navigation" (useRouter, usePathname, redirect, useParams, useSearchParams). NEVER "next/router".
• Order: (1) React/Next.js, (2) third-party packages, (3) "@/" local. Blank line between groups.

CODE COMPLETENESS:
• Complete implementation only. No "// TODO", "// ...", "// implement this", "// add your logic here", "// rest of code".
• Every async operation: explicit try/catch.
• List renders: unique, stable key props. Never use array index as key on dynamic/reorderable lists.

UI/UX QUALITY:
• Semantic HTML: <header>, <main>, <nav>, <section>, <article>, <footer>, <button>, <form>, <label>. Never <div onClick>.
• <button type="button"> for non-submit buttons. <button type="submit"> only inside forms.
• Every form input needs an associated <label> (htmlFor + id, or aria-labelledby).
• Images: descriptive alt text, or alt="" for decorative images.
• Loading states: show a spinner or skeleton. Error states: clear message with retry option.
• One <h1> per page. Logical heading hierarchy (h1 → h2 → h3). Minimum text-sm (14px) for body text.
• Responsive: works from 320px to 1440px. Use Tailwind sm:/md:/lg: breakpoints.
• Spacing: Tailwind 4-unit scale (p-4, gap-4, my-8). Adequate whitespace. No cramped layouts.
• Colors: use semantic Tailwind CSS variables (background, foreground, muted, border, primary). Dark-mode compatible.
`;

  return `Respond with ONLY the raw file content — no explanations, no markdown fences, no code block wrappers, no commentary of any kind.
${qualityRules}${fileSpecificRules}
Target file: ${task.filePath}

Relevant documentation:
${task.docsContext || "N/A"}

Dependency file contents (already written — your imports must resolve to these):
${depsSection}

Instruction:
${task.instruction}`;
}

export function buildRetryPrompt(
  previousOutput: string,
  validationError: string,
): string {
  return `The previously generated file failed validation. Fix the error AND ensure the entire file meets all code quality standards.

Respond with ONLY the complete corrected file — no explanations, no markdown fences, no commentary.

VALIDATION ERROR TO FIX:
${validationError}

REMINDER — your corrected file must also comply with:
• "use client" as absolute first line if the file uses React hooks or browser APIs
• No @ts-ignore, @ts-expect-error, or eslint-disable comments
• No unused imports (noUnusedLocals is ON — unused imports are compile errors)
• "@/" alias for all local imports — no relative paths
• No placeholder comments or incomplete sections
• Proper TypeScript types — no \`any\`
• Complete implementation — every function fully implemented

PREVIOUS OUTPUT (contains the error):
${previousOutput}`;
}

/**
 * Prompt for the system "fix & install" task.
 * Receives all generated file contents and outputs a corrected package.json
 * that includes every npm package imported across the entire project.
 */
export function buildFixerPrompt(allFiles: Record<string, string>): string {
  const filesSection = Object.entries(allFiles)
    .map(([path, content]) => `// FILE: ${path}\n${content}`)
    .join("\n\n---\n\n");

  return `You are auditing a generated Next.js project. Your ONLY job is to output a corrected package.json.

TASK:
1. Scan every import statement in every file below.
2. Identify all npm packages (not relative paths, not Node built-ins like "path", "fs", "crypto").
3. Output a complete, valid package.json that includes every required package.

MANDATORY VERSIONS — use these exactly, do not change them:
- next: "${LATEST_VERSIONS["next"]}"
- react: "${LATEST_VERSIONS["react"]}"
- react-dom: "${LATEST_VERSIONS["react-dom"]}"
- typescript: "${LATEST_VERSIONS["typescript"]}" (devDependency)
- tailwindcss: "${LATEST_VERSIONS["tailwindcss"]}" (devDependency)
- @tailwindcss/postcss: "${LATEST_VERSIONS["@tailwindcss/postcss"]}" (devDependency)

RULES:
- Keep "scripts": { "dev": "next dev", "build": "next build", "start": "next start", "lint": "next lint" }
- Put @types/* packages and build tools in devDependencies
- Do NOT include autoprefixer — Tailwind v4 does not need it
- Do NOT include packages that are not actually imported
- If a package is imported but you are not sure of its version, use "latest"
- Output ONLY the raw JSON — no markdown fences, no commentary

GENERATED FILES:
---
${filesSection}`;
}

/**
 * Prompt to fix a file that has TypeScript errors from the isolated type-check.
 * Used during the per-task retry loop.
 */
export function buildTypecheckFixPrompt(
  task: Task,
  dependencyFileContents: Record<string, string>,
  typecheckErrors: { line: number; col: number; message: string }[],
  previousOutput: string,
): string {
  const errorList = typecheckErrors
    .map((e) => `  Line ${e.line}:${e.col} — ${e.message}`)
    .join("\n");

  return `${buildTaskExecutorPrompt(task, dependencyFileContents)}

---
IMPORTANT: Your previous output for this file failed TypeScript type-checking.
Fix ALL of the following errors before responding:

${errorList}

PREVIOUS OUTPUT (contains the errors):
${previousOutput}`;
}

/**
 * Prompt to fix a file that caused errors in the full `next build`.
 * Used during the post-build repair loop.
 */
export function buildBuildFixPrompt(
  task: Task,
  dependencyFileContents: Record<string, string>,
  buildErrors: { file: string; message: string }[],
  previousOutput: string,
  allProjectFiles: Record<string, string>,
): string {
  const errorList = buildErrors.map((e) => `  ${e.message}`).join("\n");

  const otherFilesSection = Object.entries(allProjectFiles)
    .filter(([p]) => p !== task.filePath)
    .slice(0, 20) // cap to avoid huge prompts
    .map(([p, c]) => `// FILE: ${p}\n${c}`)
    .join("\n\n---\n\n");

  return `${buildTaskExecutorPrompt(task, dependencyFileContents)}

---
CRITICAL: The generated project FAILED to build with "next build". You must fix this file.

BUILD ERRORS IN THIS FILE (${task.filePath}):
${errorList}

OTHER PROJECT FILES FOR CONTEXT (do not modify these, only fix the target file):
${otherFilesSection}

PREVIOUS OUTPUT (contains the errors):
${previousOutput}`;
}
