import { exec } from "child_process";
import { promisify } from "util";
import { existsSync } from "fs";
import path from "path";
import { NextResponse } from "next/server";

const execAsync = promisify(exec);

/**
 * POST /api/setup
 * Runs stack-specific CLI setup commands after npm install but before
 * LLM file generation. Idempotent — safe to call multiple times.
 *
 * Body: { projectPath: string; stack: string[] }
 *
 * Currently handled:
 *  - "shadcn": npx shadcn@latest init -y, then add a comprehensive set of
 *              components so the LLM can import them without generating them.
 */
export async function POST(req: Request): Promise<NextResponse> {
  let body: { projectPath?: unknown; stack?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { projectPath, stack } = body;

  if (typeof projectPath !== "string" || !projectPath.trim()) {
    return NextResponse.json(
      { error: "projectPath must be a non-empty string" },
      { status: 400 },
    );
  }

  if (!existsSync(projectPath)) {
    return NextResponse.json(
      { error: `Directory not found: ${projectPath}` },
      { status: 400 },
    );
  }

  const selectedStack: string[] = Array.isArray(stack)
    ? (stack as string[])
    : [];
  const results: Record<string, string> = {};

  // ── shadcn/ui ─────────────────────────────────────────────────────────────
  if (selectedStack.includes("shadcn")) {
    const componentsJson = path.join(projectPath, "components.json");

    // Init (idempotent — shadcn skips if already configured)
    if (!existsSync(componentsJson)) {
      try {
        const { stdout } = await execAsync(
          "npx shadcn@latest init -y --base-color zinc",
          { cwd: projectPath, timeout: 120_000 },
        );
        results["shadcn-init"] = stdout.trim() || "ok";
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return NextResponse.json(
          { error: `shadcn init failed: ${msg}` },
          { status: 500 },
        );
      }
    } else {
      results["shadcn-init"] = "skipped (already initialized)";
    }

    // Add a comprehensive set of components that cover the vast majority of apps.
    // Any that already exist are silently skipped by shadcn.
    const SHADCN_COMPONENTS = [
      "button",
      "card",
      "input",
      "textarea",
      "label",
      "badge",
      "avatar",
      "separator",
      "skeleton",
      "tabs",
      "dialog",
      "alert-dialog",
      "select",
      "checkbox",
      "switch",
      "scroll-area",
      "dropdown-menu",
      "tooltip",
      "toast",
      "alert",
      "table",
      "progress",
    ].join(" ");

    try {
      const { stdout } = await execAsync(
        `npx shadcn@latest add ${SHADCN_COMPONENTS} -y --overwrite`,
        { cwd: projectPath, timeout: 180_000 },
      );
      results["shadcn-add"] = stdout.trim() || "ok";
    } catch (err) {
      // Non-fatal: some components may not support the current Tailwind version.
      // Log and continue — the LLM will generate missing ones.
      const msg = err instanceof Error ? err.message : String(err);
      results["shadcn-add-warning"] = msg;
    }
  }

  // ── Prisma ────────────────────────────────────────────────────────────────
  // `npx prisma init` creates prisma/schema.prisma and a .env stub.
  // Idempotent — skipped if the schema file already exists.
  if (selectedStack.includes("prisma")) {
    const schemaPath = path.join(projectPath, "prisma", "schema.prisma");
    if (!existsSync(schemaPath)) {
      try {
        const { stdout } = await execAsync("npx prisma init", {
          cwd: projectPath,
          timeout: 60_000,
        });
        results["prisma-init"] = stdout.trim() || "ok";
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        // Non-fatal: schema can be generated by the LLM as a fallback
        results["prisma-init-warning"] = msg;
      }
    } else {
      results["prisma-init"] = "skipped (already initialized)";
    }
  }

  // ── Drizzle ───────────────────────────────────────────────────────────────
  // No CLI init required — the LLM generates drizzle.config.ts and the schema.
  // Nothing to do here; just record that it was requested.
  if (selectedStack.includes("drizzle")) {
    results["drizzle"] = "no init required — config generated by LLM";
  }

  // ── Firebase / Firestore / Firebase Auth ──────────────────────────────────
  // No CLI init required — the LLM generates lib/firebase/config.ts etc.
  if (
    selectedStack.includes("firestore") ||
    selectedStack.includes("firebase-auth")
  ) {
    results["firebase"] = "no init required — config generated by LLM";
  }

  // ── NextAuth / Clerk / Stripe ─────────────────────────────────────────────
  // No CLI init required — the LLM generates all necessary config files.
  for (const pkg of ["nextauth", "clerk", "stripe"] as const) {
    if (selectedStack.includes(pkg)) {
      results[pkg] = "no init required — config generated by LLM";
    }
  }

  return NextResponse.json({ success: true, results });
}
